Total review
reagento/dishka pull request #20
Opened 2024-01-28 19:42 UTC by Tishka17

2024-01-28 23:02 UTC, pomponchik commented on src/dishka/dependency_source.py
> +    VALUE = "value"
🤔

2024-01-29 17:04 UTC, zhPavel requested changes

2024-01-29 18:08 UTC, Tishka17 commented on src/dishka/container.py
> +        return ContextWrapper(self._get_child(context, with_lock))
1. Lock must be unique per scope. Concurrent scopes do not need to be synchronized. Only concurrent usage of safe scoped-containers. E.g. requesting APP dependency from two concurrent Request scopes should be synchronized
2. I suppose that typical case is to Synchronize APP dependencies but not Request ones.

2024-01-29 18:09 UTC, Tishka17 commented on src/dishka/container.py
> +        return self.parent_container.get(dependency_type)
I suppose that typical case is to have 2 scopes (though we have more). So let's keep in mind for future

2024-01-29 23:09 UTC, Tishka17 commented on src/dishka/async_container.py
> +            self.lock = Lock()
сделал пока фабрику аргументом, интерфейс вынесу потом

2024-03-04 23:10 UTC, closed without merging